version: '3.1'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dblanguages
  redis:
    image: redis:5
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - 8081:8081
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis